sudo: required
services:
  - docker

before_install:
  - docker build -t 22101992/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  22101992/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region:  "us-west-1"
  app: "docker_test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-us-west-1-608294016219"
  bucket_path: "docker_test"
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


